# This workflow will run every time a new release is created.
# It will first build the plugin using Maven, then publish it to GitHub packages and finally attach the artifacts to the release

name: Maven build and deploy on release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Setup workspace
      run: mkdir artifacts

    - name: Build with Maven
      run: |
        mvn -B install package --file pom.xml
        cp Minepacks/target/M*.jar artifacts/

    - name: Publish to GitHub Packages Apache Maven
      run: 'mvn deploy -pl Minepacks-API,Minepacks -s $GITHUB_WORKSPACE/settings.xml "-DaltDeploymentRepository=github::default::https://maven.pkg.github.com/GeorgH93/Minepacks"'
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Build with Maven (Standalone)
      run: |
        mvn -B clean install package --file pom.xml -P Standalone,ExcludeBadRabbit
        mv Minepacks/target/M*-Standalone.jar artifacts/

    - name: Build with Maven (Release)
      run: |
        mvn -B clean package --file pom.xml -P Release
        mv Minepacks/target/M*-Release.jar artifacts/

    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'artifacts/M*'
